iamAyushChamoli/hacktoberfest-24

src/components/BadgeList.jsx
- **Related Issue**: #(Issue Number)
```
issue-<your-name>-<PR-number>
```
```
```
Please include screenshots or videos of your changes (especially if the changes are UI/UX related).
Please provide any additional information that might be helpful for the maintainers or other contributors to understand your changes.
=> Test Badge 1

.vaunt/config.yaml
Fixed the YAML format of the Vaunt config and a couple spelling errors.
=> fix: vaunt configuration format

.vaunt/config.yaml
Use correct image url links for Vaunt achievement icons.
=> fix: use content url for achievement icons

abt/Badge.md, abt/Compete.md, abt/Explore.md, abt/GithHub_Git.md, abt/Network.md, abt/Portfolio.md, package-lock.json, src/components/Benefits.jsx, src/constants/index.js
added markdown files for benefits links
updated constants benefits links
- Now learn more are behaving as links in benefits section and redirecting to the markdown files on their respective files
- **Related Issue**: #15 
```
issue-<vineet singh>-<15>
```
```
```
Please include screenshots or videos of your changes (especially if the changes are UI/UX …
=> added link behaviour in learn more benefits section

src/participants/participants.js
- **Related Issue**: #29 
```
issue-<your-name>-<PR-number>
```
```
```
Please include screenshots or videos of your changes (especially if the changes are UI/UX related).
Please provide any additional information that might be helpful for the maintainers or other contributors to understand your changes.
=> issue-udaykiran-1

src/components/Footer.jsx
Increased the footer icons size 
- Fixers : #35 
Before : 
After:
=> FIX: Increased Footer Icons size -Umesh Kumar -#37

src/participants/participants.js
Added External pr's in Participation.js
ADD :  #51 
=> ADD: Added External PR's In participation

src/index.css
Fixed : #19
Added styles to scrollbar.
=> pr-add-mishratanishq-52

src/components/Header.jsx, src/participants/participants.js
So I saw the site in Mobile view and noticed that the Navmenu is Overlapping NavIcon which was not right so i fixed that as it felt necessary.
- **Related Issue**: #53 
```
issue-divyanshuchaurasiya-1
```
=> NavSection Fix newBranch

package-lock.json, package.json, src/components/Header.jsx, src/components/Heading.jsx, src/components/Leaderboard.jsx, src/constants/scroll.js, src/index.css
- **Related Issue**: #58 
- [✓ ] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and followed the process outlined there.
- [ ✓] I have added tests that prove my fix or feature works as expected (if applicable).
- [ ✓] I have updated necessary documentation (if applicable).
- [✓ ] My changes are free from any merge conflicts.
- [✓ ] I have added my name and PR details to the `participants/participants.js` file (if contributing in Tier 1 or 2).
```
issue-pratik …
```
=> Responsive Navbar

abt/Compete.md
Update abt/Compete.md for "Compete with your peers card"
- **Related Issue**: #21 
=> pr-add-tanuj-64

src/components/Header.jsx
Fixed the cursor not changing on hovering some navbar contents
- **Fix*: #78 
ScreenShot: 
Before :  
After: 
=> FIX : Navbar Hover Issue 

abt/Badge.md
The updates in this PR involve adding detailed descriptions and visuals for the badges offered during Hacktoberfest GEU. Each badge type (Participation Badge, Active Participation Badge, Master Badge) now includes:
Clear descriptions explaining the criteria for earning each badge.
Visual representations of the badges to enhance clarity.
Emphasis on the value and uniqueness of the limited edition badges.
pr-add-Ayushi Gaur -89
=> Updated Badges.md

src/participants/participants.js
Updated the participation js file 
- **ADD PR**: #76 
=> pr-update-Umesh Kumar

src/assets/svg/ClipPath.jsx, src/components/Benefits.jsx
The card styles have been updated to feature rounded corners, enhancing the overall visual appeal and modernizing the design. The  `borderRadius` was increased from `10px to 80px`, providing a softer look that contributes to a more inviting user interface. Additionally, the background styling now uses the `background property` for gradients, replacing the previous `borderImage `approach. The `ClipPath` component was also modified to create rounded corners using a new path definition, ensuring a seamless integration with the updated card design. These changes collectively improve the aesthetics and user experience, making the cards feel more contemporary and user-friendly.
- **Related Issue**: #40  …
=> pr-add-ayushimaithani-40

src/components/Leaderboard.jsx, src/index.css
I have updated the leaderboard UI to make it more **responsive and cleaner**. The new design ensures that the leaderboard is more readable and takes up less space compared to the previous version. The contributors now lie one below the other, and the ranking is clearly highlighted, providing a better user experience.
**Related Issue:** [https://github.com/iamAyushChamoli/hacktoberfest-24/issues/84](url)
=> issue-kaushikikhabri-84

src/components/Badges.jsx
=> issue-Lokeshsuwalka05

src/components/Leaderboard.jsx, src/index.css
Reverts iamAyushChamoli/hacktoberfest-24#100
##Reason
---
This PR resulted in the loss of participation data of some participants.
=> Revert "issue-kaushikikhabri-84"

src/participants/umesh.js
Added the missing files in umesh.js file 
=> UPDATE : Updated Umesh.js file

README.md
- **Related Issue**: #109 
```
issue-<your-name>-<PR-number>
```
```
```
Please include screenshots or videos of your changes (especially if the changes are UI/UX related).
Please provide any additional information that might be helpful for the maintainers or other contributors to understand your changes.
=> reagarding issue #109

src/components/Hero.jsx
=> pr-add-shubhanshu-108

CONTRIBUTING.md
=> Regarding issue #112

src/participants/mohit.js
PR Details: 
This PR is made for 2 issues.
Name: Mohit rana
GitHub Username: mohitranag18
External PR Number: 183
Link to External PR: 
https://github.com/GarimaSingh0109/Resum-Resume/pull/183
External Repository: https://github.com/GarimaSingh0109/Resum-Resume
Brief Description of Your Contribution:
Improved Text Contrast:
You noticed that text colors were not making sufficient contrast with their backgrounds, which made the text hard to read and created a poor user experience. You corrected this by selecting appropriate color schemes that follow contrast guidelines, ensuring that the text is easily readable in all sections of the website.
Unified Color Scheme:
The website was inconsistent in terms of color usage, especially in areas like the footer, which didn't match the rest of the …
=> pr-add-mohitranag18-101,63

src/participants/mohit.js
PR Details
This PR is to update participant record for issue 116:
Name: Mohit Rana
GitHub Username: mohitranag18
External PR Number: 128
Link to External PR: 
https://github.com/RamakrushnaBiswal/PlayCafe/pull/128
External Repository: https://github.com/RamakrushnaBiswal/PlayCafe
Brief Description of Your Contribution:
Description :
This introduces a 'Today's Special' section to the Menu page, featuring three cards for Coffee, Drink, and Food items. Key features include:
Dynamic Content: Each card displays a special item that changes daily, providing variety to users by rotating through a predefined list of 3 items per category.
Fixed Image Dimensions: Ensures consistent card sizes with fixed image width and height, regardless of image size, using object-fit to maintain proper scaling. …
=> pr-add-mohitranag18-128

abt/Network.md
- **Related Issue**: #(#24)
-This PR updates the network.md with related content
- [x ] I have added tests that prove my fix or feature works as expected (if applicable).
```
issue-<your-name>-<PR-number>
```
```
```
Please include screenshots or videos of your changes (especially if the changes are UI/UX related).
Please provide any additional information …
=> chore: update network.md content

src/components/Footer.jsx
@iamAyushChamoli 
successfully changes footer.
Fixes: #124
Before:
After:
=> changes done in footer

src/participants/mohit.js
This PR is to update participant record for issue 135:
Name: Mohit Rana
GitHub Username: mohitranag18
External PR Number: 691
Link to External PR:  https://github.com/aditya-bhaumik/Pathsphere/pull/691
External Repository: https://github.com/aditya-bhaumik/Pathsphere
Brief Description of Your Contribution:
**Details**
Converted forum-section elements into card format.
Applied a yellow, white, and grey color theme for consistency with the overall design.
Implemented a responsive layout using flexbox, where forum-section cards are displayed horizontally and forum-posts are vertically aligned inside each section.
Added a hover effect to the cards for better interactivity.
Incorporated media queries to ensure mobile responsiveness, with sections stacking vertically on smaller screens.
=> pr-add-mohitranag18-691

abt/Portfolio.md, package-lock.json, package.json
Added a new markdown file build-github-portfolio.md
Outlines event details focused on improving GitHub portfolios
Key topics include:
Optimizing GitHub profiles
Creating standout READMEs
Boosting portfolio visibility (GitHub Pages, pinned repositories)
Includes hands-on workshops, code reviews, and networking opportunities
=> Build GitHub portfolio

README.md, src/components/BadgeList.jsx, src/participants/Anas.js
This PR addresses the issue of misalignment of the Vaunt badges on small screens. The badges were previously aligned to the left, which disrupted the visual consistency. The changes ensure that the badges are centered on smaller screens, improving the overall design and user experience.
- **Related Issue**: #142 
- 
```
issue-AnasAli30-142
```
Before:
After:
=> issue-AnasAli30-142
